# 使用 Python 3.12 的官方镜像作为基础镜像
FROM python:3.12

# 设置工作目录
WORKDIR /app

# 将 requirements.txt 复制到工作目录
COPY requirements.txt .

# 安装 Python 依赖包
RUN pip install --no-cache-dir -r requirements.txt

# 复制当前目录的所有内容到工作目录
COPY . .

# 暴露容器内的端口（如果需要具体端口，请替换8888）
EXPOSE 8888

# 设置环境变量（可选）
# ENV TELEGRAM_BOT_TOKEN=your_bot_token
# ENV TELEGRAM_CHAT_ID=your_chat_id

# 设置容器启动时执行的命令
CMD ["python", "main.py"]